name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1 # Replace with your AWS region

      - name: Deploy to EC2 using SSM
        uses: aws-actions/ssm-run-command@v1
        with:
          document-name: "AWS-RunShellScript"
          targets: "InstanceIds=your-ec2-instance-id" # Replace with your EC2 instance ID
          parameters: |
            commands=[
              "cd /path/to/your/application",
              "git pull origin main",
              "cd backend",
              "npm install",
              "cd ../frontend",
              "npm install",
              "npm run build",
              "node server.js &"
            ]
