name: asia-workflow
run-name: ${{ github.environment }} is learning GitHub Actions

on:
  push:
    branches:
      - master

jobs:
  read-hello-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
      - name: read sayHello file
        run: node sayHello.js
