name: Deploy to EC2

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Describe instances
        id: describe
        run: |
          aws ec2 describe-instances --filters "Name=tag:Name,Values=boule" --query "Reservations[].Instances[?State.Name == 'running'].InstanceId[]" --output text > instance_id.txt

      - name: Run command on EC2 instance
        if: success()
        run: |
          INSTANCE_ID=$(cat instance_id.txt)
          if [ -z "$INSTANCE_ID" ]; then
            echo "No running instances found."
            exit 1
          fi
          COMMAND_ID=$(aws ssm send-command --instance-ids $INSTANCE_ID --document-name "AWS-RunShellScript" --comment "Say Hello" --parameters '{"commands":["echo \'sayhello\'"]}' --query "Command.CommandId" --output text)
          aws ssm wait command-executed --command-id $COMMAND_ID --instance-id $INSTANCE_ID
          aws ssm get-command-invocation --command-id $COMMAND_ID --instance-id $INSTANCE_ID
