name: Update EC2 Instance
on: [push]
jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        run: |
          echo "${{ secrets.PRIVATE_KEY }}" | base64 --decode > private_key.pem
          chmod 600 private_key.pem

      - name: Connect to EC2 instance and update application
        run: |
          ssh -o StrictHostKeyChecking=no -i private_key.pem ubuntu@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
            cd /path/to/your/application

            # Ensure the working directory is clean
            git fetch origin
            git reset --hard origin/main
            git clean -fd

            # Backend update
            cd backend
            npm install
            pm2 restart all # Assuming you are using PM2 to manage your Node.js processes

            # Frontend update
            cd ../frontend
            npm install
            npm run build
            pm2 restart serve # Restart your frontend server if using PM2
          EOF
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          EC2_PUBLIC_IP: ${{ secrets.EC2_PUBLIC_IP }}
