name: SSH Example

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH key
        run: |
          echo "${{ secrets.PRIVATE_KEY }}" > private_key.pem
          chmod 600 private_key.pem

      - name: SSH into EC2 instance
        env:
          EC2_PUBLIC_IP: ${{ secrets.EC2_PUBLIC_IP }}
        run: |
          ssh -o StrictHostKeyChecking=no -i private_key.pem -tt ubuntu@${{ env.EC2_PUBLIC_IP }} << 'EOF'
          ssh -o StrictHostKeyChecking=no -i private_key.pem -tt ubuntu@${{ env.EC2_PUBLIC_IP }} << 'EOF'
            echo "Hello from the first SSH session"
            exit
          EOF
      - name: Clean up
        run: |
          rm private_key.pem
