name: Update EC2 Instance
on: [push]
jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.PRIVATE_KEY }}" > ~/.ssh/private_key.pem
          chmod 600 ~/.ssh/private_key.pem

      - name: Connect to EC2 instance and update application
        run: |
          ssh -o StrictHostKeyChecking=no -i private_key.pem ubuntu@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
          echo hello
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          EC2_PUBLIC_IP: ${{ secrets.EC2_PUBLIC_IP }}
# name: read-private-key
# on: [push]
# jobs:
#   read:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Read private key
#         env:
#           PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
#         run: |
#           echo "Private Key: $PRIVATE_KEY"
