name: Deploy to EC2

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Deploy to EC2 using SSM
        run: |
          # Run commands on EC2 instance using AWS CLI
          COMMAND_ID=$(aws ssm send-command \
            --document-name "AWS-RunShellScript" \
            --targets "Key=instanceids,Values=i-07a9b173f677b146a" \
            --parameters 'commands=["cd github-actions-test","echo 'hi from the sky' &"]' \
            --query "Command.CommandId" \
            --output text)

          echo "Command ID: $COMMAND_ID"

      - name: Check SSM Command Status
        run: |
          # Check the status of the command execution
          aws ssm list-commands \
            --command-id $COMMAND_ID \
            --query "Commands[0].Status" \
            --output text
